// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package gradebook.domain;

import gradebook.domain.Professor;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Professor_Roo_Configurable {
    
    declare @type: Professor: @Configurable;
    
}
